const countries = {
  hongkong: '🇭🇰',
  'mainland china': '🇨🇳',
  japan: '🇯🇵',
  korea: '🇰🇷',
  india: '🇮🇳',
  malaysia: '🇲🇾',
  indonesia: '🇮🇩',
  philippines: '🇵🇭',
  canada: '🇨🇦',
  'U.S.A': '🇺🇸',
  mexico: '🇲🇽',
  brazil: '🇧🇷',
  argentina: '🇦🇷',
  france: '🇫🇷',
  belgium: '🇧🇪',
  germany: '🇩🇪',
  italy: '🇮🇹',
  netherlands: '🇳🇱',
  switzerland: '🇨🇭',
  spain: '🇪🇸',
  'U.K': '🇬🇧',
  austria: '🇦🇹',
  greece: '🇬🇷',
  sweden: '🇸🇪',
  russian: '🇷🇺',
  australia: '🇦🇺',
  'new zealand': '🇳🇿',
  palau: '🇵🇼',
  myanmar: '🇲🇲',
  cambodia: '🇰🇭',
  brunei: '🇧🇳',
  thailand: '🇹🇭',
};

module.exports = countries;
